// Generated by CoffeeScript 2.6.1
(function() {
  var canvas;

  canvas = document.getElementById('canvas');

  canvas.width = window.innerWidth;

  canvas.height = window.innerHeight;

  document.body.onresize = function() {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
  };

  CP.Runner.runGraphical(canvas, function(cart) {
    cart.leftPressed = cart.angle < 0;
    cart.rightPressed = cart.angle > 0;
  });

}).call(this);
